### ISSUE TITLE
Play Sprint Plan 2019-07-29

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#100]
* [x] Update to Akka 2.6.0-M5 @marcospereira
	* [x] playframework/playframework#9506
	* [x] Play: Fix "Expected IOE, got akka IOE" playframework/playframework#9491
	    * related to https://typesafe.slack.com/archives/C1ETEPM36/p1562713711239300
	    * been consistently failing the cron jobs for a few days now
	* [x] Lagom: https://github.com/lagom/lagom/pull/2137
* [ ] playframework/playframework#9278 Play CQRS / Event Sourcing (incubating module)
	- [ ] playframework/playframework#9277 DI for ClusterSharding Typed @renatocaval
    - [x] ~list of "must-haves" for this epic @renatocaval~ (too late)
* [ ] Lagom: Land "shopping-cart-java read-side processor" lagom/lagom-samples#60 @renatocaval
	* having sample apps with that which can be deployed and up/down-scaled will help test lagom/lagom#2055
* [ ] Lagom: pause/resume projections "must have"s lagom/lagom#2052
* [ ] Play: DI for typed actors playframework/playframework#8999 @dwijnand
* [x] Update & fix setup for MiMa 0.5.0 @dwijnand
	* [x] Lagom master lagom/lagom#2110
	* [x] Lagom 1.5 lagom/lagom#2133
	* [x] Lagom 1.4 lagom/lagom#2134
	* [x] Play master playframework/playframework#9533
	* [x] Play 2.7 playframework/playframework#9534
	* [x] ~Play 2.6 playframework/playframework#9535~
		* lots of warnings running locally
		* skipping on assumption of no (significantly) new Play 2.6 releases
* [ ] Play 2.8.0-M4 release
* [ ] Lagom 1.6.0-M5 release
* [ ] Tweak CI - distinct requirements for PR, branch & cron builds playframework/play-meta#103

###### Metadata

* Dates: 2019-07-29 - 2019-08-09
* [Previous Sprint](https://github.com/playframework/play-meta/issues/95)
* Support Rota: Renato then Marcos
* Person days: 13.5/30 (Ignasi -10, Renato -5, Dale -1.5)
