### ISSUE TITLE
Play Sprint Plan 2019-08-12

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#105]
## Scope

* [x] Play: DI for typed actors playframework/playframework#8999 @dwijnand
* [x] [Play 2.8.0-M4 release](https://github.com/playframework/play-meta/issues/107)
* [x] [Lagom 1.6.0-M5 release](https://github.com/playframework/play-meta/issues/108)
* [x] [Lagom 1.4.x release](https://github.com/playframework/play-meta/issues/111) (cross-build fix)
    * [x] https://github.com/lagom/lagom/pull/2161
* [x] Play: scripted tests not passing for Java 11 @dwijnand playframework/playframework#9575
* [ ] Lagom: pause/resume projections "must have"s lagom/lagom#2052
* [ ] playframework/playframework#9278 Play CQRS / Event Sourcing (incubating module)
	- [ ] playframework/playframework#9277 DI for ClusterSharding Typed @renatocaval
* [x] ~playframework/play-meta#104 Simplify the setup of Play docs~ (pushed to Dec) @dwijnand 
* [ ] Lagom: Land "shopping-cart-java read-side processor" lagom/lagom-samples#60 
* [x] ~Tweak CI - distinct requirements for PR, branch & cron builds playframework/play-meta#103~ (pushed to Dec)

###### Metadata

* Dates: 2019-08-12 - 2019-08-23
* [Previous Sprint](https://github.com/playframework/play-meta/issues/100)
* Support Rota: Dale then Ignasi
* Person days: 15/30 (-5 Ignasi, -10 Renato)
