### ISSUE TITLE
Play Sprint Plan 2019-08-26

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#109]
## Draft

* [x] [Release Lagom 1.5.2](https://github.com/playframework/play-meta/issues/112) (with https://github.com/lagom/lagom/pull/2191) @dwijnand 
* [x] Pause/Resume projections ([epic](https://github.com/lagom/lagom/issues/2052)):
  - [x] https://github.com/lagom/lagom/pull/2205 Make all Projections API usable from `javadsl`
  - [x]  https://github.com/lagom/lagom/pull/2124 implement `UpdateSuccess` and `UpdateFailure`
  - [x]  https://github.com/lagom/lagom/issues/2233 - manual tests in a deployment
  - [x]  https://github.com/lagom/lagom/pull/2128 integration and `scripted` tests
    - [x] https://github.com/lagom/lagom/pull/2231
    - [x] https://github.com/lagom/lagom/pull/2242
  - [x]  https://github.com/lagom/lagom/pull/2130 Make configurable
* [ ] Refine [Play-CQRS Epic](https://github.com/playframework/playframework/issues/9278) - produce a list of tasks so it can be used in a vanila Play app
* [x] Lagom: Land "shopping-cart-java read-side processor" lagom/lagom-samples#60 @renatocaval - can be fixed once https://github.com/lagom/lagom/pull/2211 is merged and we have a new Lagom milestone. We decided to fix it because we suspected that the issue may have come to the surface because of new Cluster Bootstrap integration
 
###### Metadata

* Dates: 2019-08-26 - 2019-09-06
* [Previous Sprint](https://github.com/playframework/play-meta/issues/105)
* Support Rota: @renatocaval  then @marcospereira 
* Person days: 21/30
  * @marcospereira out for five days (Aug 26 to Aug 30)
  * @dwijnand out for 4 days (26 Aug & 2-6 Sept)

**Comment by ignasi35** [comment]
> * [ ]  Release Lagom 1.5.2 (with [lagom/lagom#2191](https://github.com/lagom/lagom/pull/2191))

We should followup with play-grpc: https://github.com/playframework/play-grpc/issues/124#issuecomment-527052597

**Comment by dwijnand** [comment]
> - [ ] Refine [Play-CQRS Epic](https://github.com/playframework/playframework/issues/9278) - produce a list of tasks so it can be used in a vanila Play app

is the only thing we didn't achieve this sprint.  Pretty successful!
