### ISSUE TITLE
Play Sprint Plan 2019-09-23

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#119]
* [x] Adopt https://github.com/lightbend/config/pull/619 brought in with `Akka 2.6.0 M7` @dwijnand 
	* [x] https://github.com/playframework/playframework/pull/9670
* [x] Switch Play to Sonatype bundle uploading @dwijnand
	* [x] https://github.com/playframework/interplay/pull/89
	* [x] https://github.com/playframework/playframework/pull/9651
* [x] Latest Milestones of Play/Akka/Akka HTTP [lagom/lagom#2267](https://github.com/lagom/lagom/pull/2279)
    * [x] Testing compatibility between proto2 and 3 - use https://github.com/renatocaval/lagom-1.6-playground for quick cluster testing
* [x] Lagom projections API docs: lagom/lagom#2269
* [x] Release Lagom 1.6.0-M6 [playframework/play-meta#117](https://github.com/playframework/play-meta/issues/117) @dwijnand
* [ ] Investigate what is needed to port a Lagom application to use Akka Persistence Typed
    * [x] https://github.com/lagom/lagom-samples/pull/97 (not to be merged), for both Java and Scala
    * [x] Dependency Injection for ClusterSharding Typed: https://github.com/playframework/playframework/pull/9503.
    * [ ] Lagom: add an adapter from Lagom tagging to Akka Persistence Typed tagging @renatocaval 
* [x] ~Provide `EntityFactory` that makes it easier to shard persitence entities~ - after discussing with Akka Team, it became clear that `EntityFactory` is not offering much value.
* [ ] Play: document how to use Akka Persistence Typed
* [ ] Lagom: document how to migrate to Akka Persistence Typed from existing Lagom PE code (includes data compat, migrating events, unit tests...)
    * Scala users need to learn how to use Akka Jackson for the commands (ActorRef[Reply] issue)
    * Java users need to learn how to keep business id around for tagging
    * Java users need to learn how to remove `PersistenceId` separator
    

###### Metadata

* Dates: 2019-09-23 - 2019-10-04
* [Previous Sprint](https://github.com/playframework/play-meta/issues/114)
* Support Rota: Dale then Renato
* Person days: 26/30
	* Ignasi out 2
	* Dale out 2
