### ISSUE TITLE
Play Sprint Plan 2019-10-07

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#123]
* [x] @dwijnand Play + Akka v2.6.0-M8 (`ActorContext` DI change) [play#9712](https://github.com/playframework/playframework/pull/9712) [play#9715](https://github.com/playframework/playframework/pull/9715)
* [ ] @marcospereira Solve dependency injection for typed Scheduler
    * [ ] Figure it out if it needs to be a singleton or not
* [x] @dwijnand Play: [Release v2.8.0-M6](https://github.com/playframework/play-meta/issues/124) (w/ Akka v2.6.0-M8)
* [x] @ignasi35 Lagom: Release notes for [v1.6.0-M6](https://github.com/lagom/lagom/releases/tag/1.6.0-M6)
* [x] @renatocaval Lagom: add a tagging adapter for Akka Persistence Typed tagging [lagom#2312](https://github.com/lagom/lagom/pull/2312)
* [ ] @dwijnand Lagom: [Release v1.6.0-M7](https://github.com/playframework/play-meta/issues/125) (w/ Akka v2.6.0-M8 & Play v2.8.0-M6) - https://github.com/lagom/lagom/pull/2350
* [ ] Lagom: document uses of Akka Persistence Typed
    * [ ] @renatocaval How to do persistence using Akka Persistence Typed in Lagom applications
        * [ ] Scala users need to learn how to use Akka Jackson for the commands (`ActorRef[Reply]` issue)
    * [ ] @renatocaval How to migrate from classic Lagom persistence API to Akka Persistence Typed
        * [ ] Java users need to learn how to remove `PersistenceId` separator
    * [ ] @ignasi35 Adapt our sbt seeds to use Akka Persistence Typed (1.6.x branches)
    * [ ] @ignasi35 Adapt our maven archetype to use Akka Persistence Typed
* [ ] Adapt lagom-samples to use Akka Persistence Typed (1.6.x branch) - blocked, awaiting 1.6.0-M7
  * [ ] @renatocaval shopping-cart
  * [ ] @marcospereira mixed-persistence
  * [ ] @marcospereira couchbase-persistence

###### Metadata

* Dates: 2019-10-07 - 2019-10-18
* [Previous Sprint](https://github.com/playframework/play-meta/issues/119)
* Support Rota: Ignasi then Marcos
* Person days: 24/30
	* Renato out 3
	* Dale out 2
	* Marcos out 1

## Scope for next sprint

* [ ] Play: add a sample (to play-samples) using Akka Persistence Typed + advertise in 2.8 highlights
    * [ ] Cluster sharding
    * [ ] Cluster formation
* [ ] Jackson 2.10 after Akka 2.6.0-RC1

## Backlog

* lagom and play samples
    * lagom gRPC samples issues
        * lagom-grpc-scala not using latest milestone
        * latest proto-to-java generators use deprecated API (both Akka-grpc and protoc itself)
        * miss-alignemt on Akka-HTTP versions (Play and Lagom use 10.1.0, akka-grpc uses 10.1.9). Causes runtime errors. Requires users to add dependencyOverrides
* akka-discovery-service-loc is DNS_SVR eager (https://github.com/lagom/lagom/issues/2299)
* ServiceClientModule breaking Lagom mocking tests https://github.com/lagom/lagom/issues/2307

**Comment by marcospereira** [comment]
Other things discussed last week.

----

## Requires attention next sprint

- @ignasi35 release milestones with Akka 2.6.0-M8
- Jackson 2.10
  - @marcospereira play-json we can already update it
- Finish the work around Play-CQRS
  - Tagging adapter
  - Reference docs
  - Sample application
- lagom and play samples
    - lagom gRPC samples issues
        - lagom-grpc-scala not using latest milestone
        - latest proto-to-java generators use deprecated API (both Akka-grpc and protoc itself)
        - miss-alignemt on Akka-HTTP versions (Play and Lagom use 10.1.0, akka-grpc uses 10.1.9). Causes runtime errors. Requires users to add dependencyOverrides

## These aren't high priority

- akka-discovery-service-loc is DNS_SVR eager (https://github.com/lagom/lagom/issues/2299)
- ServiceClientModule breaking Lagom mocking tests https://github.com/lagom/lagom/issues/2307
