### ISSUE TITLE
Play Sprint Plan 2019-10-21

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#126]
* [x] Lagom: Release [1.6.0-M7](https://github.com/playframework/play-meta/issues/125) @dwijnand
* [x] Lagom: Fix scripted tests w/ Akka 2.6 [lagom#2370](https://github.com/lagom/lagom/pull/2370) @dwijnand
* [x] ~Lagom: Release 1.6.0-M8 with fix (if necessary)~ @dwijnand
* [x] Play: DI for AskPattern's Scheduler: [play#9758](https://github.com/playframework/playframework/pull/9758) @marcospereira
* [x] Play-WS: Update Akka RC1 [play-ws#404](https://github.com/playframework/play-ws/pull/404) @marcospereira
* [x] Play-WS: Release 2.1.0-M7 @dwijnand 
* [x] Play: Update w/ Akka RC1 + Jackson 2.10 [play#9723](https://github.com/playframework/playframework/pull/9723) @marcospereira
* [x] Play: Release [2.8.0-RC1](https://github.com/playframework/play-meta/issues/128) (w/ Akka v2.6.0-RC~1~2) @dwijnand
    * [x] @marcospereira Support RangeResult where the Source provider can pre-seek to the start [play#9513](https://github.com/playframework/playframework/pull/9513)
* [x] Fix sbt-pgp problem in lagom-master, blocking release @dwijnand 
* [x] Lagom: [Release 1.6.0-RC1](https://github.com/playframework/play-meta/issues/129) (w/ Play RC1+Akka RC2) @dwijnand
	* [x] Update Akka 2.6 RC2 + Play 2.8 RC1 https://github.com/lagom/lagom/pull/2400
* [ ] Lagom: document uses of Akka Persistence Typed - https://github.com/lagom/lagom/issues/2387
    * [ ] @ignasi35 Akka Persistence Typed in Lagom Epic [lagom#2387](https://github.com/lagom/lagom/issues/2387)
        * [x] [lagom#2406](https://github.com/lagom/lagom/pull/2406) Scala users need to learn how to use Akka Jackson for the commands (`ActorRef[Reply]` issue)
        * [x] Review general serialization documentaion for Scala [lagom#2348](https://github.com/lagom/lagom/issues/2348)        
    * [x] @ignasi35 Adapt our sbt seeds to use Akka Persistence Typed (1.6.x branches)
      * [x] https://github.com/lagom/lagom-scala.g8/pull/70
      * [x] https://github.com/lagom/lagom-java.g8/pull/70 
    * [x] @ignasi35 Adapt our maven archetype to use Akka Persistence Typed [lagom#2378](https://github.com/lagom/lagom/pull/2378)
* [x] Release lightbend-markdown @dwijnand 
* [ ] @ignasi35 Review AkkaTaggerAdapter's API [lagom#2390](https://github.com/lagom/lagom/pull/2390)
    * [x] It must be `@ApiMayChange` https://github.com/lagom/lagom/pull/2376
* [ ] Adapt lagom-samples to use Akka Persistence Typed (1.6.x branch)
  * [x] @marcospereira shopping-cart
     * [x] scala (blocked on release) https://github.com/lagom/lagom-samples/pull/118
     * [x] java (blocked on release) https://github.com/lagom/lagom-samples/pull/119
  * [ ] @marcospereira mixed-persistence
  * [ ] @marcospereira couchbase-persistence
* [ ] Play: port samples using Akka to Akka Typed Actors
	* [x] play-scala-secure-session-example  https://github.com/playframework/play-samples/pull/59 @dwijnand 
    * [ ] play-scala-websocket-example @marcospereira 
    * [ ] play-websocket-java-example (blocked, after scala)
* [ ] Use latest AdoptOpenJDK patched versions in CI #93 @marcospereira

###### Metadata

* Dates: 2019-10-21 - 2019-11-01
* [Previous Sprint](https://github.com/playframework/play-meta/issues/123)
* Support Rota: Renato then Dale
* Person days: 23/30
  * Renato out 5
  * Dale out <1
  * Ignasi out 1

**Comment by renatocaval** [comment]
We have two open milestones impacting 1.6.0
* [1.6.0](https://github.com/lagom/lagom/milestone/33)

**Comment by dwijnand** [comment]
There's also milestone [1.6.0-M8](https://github.com/lagom/lagom/milestone/59)

**Comment by TimMoore** [comment]
My feeling is that the two service locator issues in the 1.6.0 milestone (lagom/lagom#2299 and lagom/lagom#2354) should not be release blockers, since they could be resolved in a patch release later.
