### ISSUE TITLE
Play 1/2 Sprint Plan 2019-11-04

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#130]
* [x] @dwijnand lagom-persistence-couchbase + Lagom 1.6 RC1 [lagom#2414](https://github.com/lagom/lagom/issues/2414)
* [x] Review AkkaTaggerAdapter's API [lagom#2390](https://github.com/lagom/lagom/pull/2390)
* [x] @ignasi35 Slick shutdown down problem in shopping-cart-java tests: [lagom-samples#121](https://github.com/lagom/lagom-samples/issues/121)/[lagom#2426](https://github.com/lagom/lagom/pull/2426)
* [x] @ignasi35 Kafka exception when running tests for shopping-cart-scala: [lagom-samples#131](https://github.com/lagom/lagom-samples/pull/131)
* [x] @dwijnand Logging configuration issue in shopping-cart-java: [lagom-samples#129](https://github.com/lagom/lagom-samples/pull/129)
* [ ] @marcospereira Play-WS charset encoding https://github.com/playframework/play-ws/pull/392
* [x] @dwijnand Create new stable branches for Play 2.8.x and Lagom 1.6.x
  * [x] Retarget any PRs
  * [x] Review backport/forwardport current state, introduce new variants
  * [x] New Travis CI cron jobs
    * [x] verify after 24H
  * [x] New vegemite nightly deploy + doc deploy cron jobs [vegemite#43](https://github.com/lightbend/vegemite/pull/43)
    * [x] verify after 24H
  * [x] New whitesource project
    * [x] verify after 24H
* [x] @dwijnand [Release Lagom 1.6 RC2](https://github.com/playframework/play-meta/issues/132)
* [ ] Lagom: Akka Persistence Typed docs [lagom#2387](https://github.com/lagom/lagom/issues/2387)
  * [x] @marcospereira Lagom: Move persistence tutorial code to scala files to typecheck [lagom#2423](https://github.com/lagom/lagom/pull/2423)
  * [ ] @renatocaval Port the Scala tutorial to Java
    * [ ] rewrite ref docs
    * [ ] import java code from the lagom-samples
  * [ ] @renatocaval Lagom: Migrating to Akka Persistence Typed
    * [ ] Make all embedded code style-guide compliant (scala)
    * [ ] Writeup of the migration process (java), port [lagom#2407](https://github.com/lagom/lagom/pull/2407)
    * [ ] Make all embedded code style-guide compliant (java)
* [ ] Adapt lagom-samples to use Akka Persistence Typed (1.6.x branch)
  * [ ] @ignasi35 mixed-persistence
  * [ ] @marcospereira couchbase-persistence
    * blocked on RC1's breakage
* [ ] Play: port samples using Akka to Akka Typed Actors
  * [x] @renatocaval shopping-cart java should use `AkkaTaggerAdapter` - [lagom-samples#132](https://github.com/lagom/lagom-samples/pull/132)
  * [ ] @dwijnand play-scala-websocket-example [play-samples#62](https://github.com/playframework/play-samples/pull/62)
  * [ ] @dwijnand play-java-websocket-example [play-samples#63](https://github.com/playframework/play-samples/pull/63)
  * [ ] @dwijnand review state of samples using Play 2.8
* [ ] @marcospereira Review the state of all upstream projects https://github.com/playframework/play-meta/issues/131

###### Metadata

* Dates: 2019-11-04 - 2019-11-08
* [Previous Sprint](https://github.com/playframework/play-meta/issues/126)
* Support Rota: Ignasi
* Person days: 15/15

**Comment by TimMoore** [comment]
Are the samples problems regressions in 1.6.x or do they happen in 1.5.x too?

**Comment by dwijnand** [comment]
The couchbase one is a brand new regression from breaking the binary API of an internal class.

**Comment by TimMoore** [comment]
Right, sorry I meant the other ones.

**Comment by marcospereira** [comment]
> Are the samples problems regressions in 1.6.x or do they happen in 1.5.x too?

It is possible they are happening for 1.5.x as well, but I didn't have time to investigate it when reporting the problems. I think as soon we understand what is happening, we can validate if it happening for 1.5.x branches as well.

/cc @ignasi35.

**Comment by ignasi35** [comment]
> Are the samples problems regressions in 1.6.x or do they happen in 1.5.x too?

The Kafka one is a new problem introduced on a newly added intergation test. Nothing serious. See https://github.com/lagom/lagom-samples/pull/131

I haven't checked the slick-related issue on the `shopping-cart-java` sample yet.
