### ISSUE TITLE
Play Sprint Plan 2019-11-18

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#133]
## Play 2.8.0 Release

* [x] @marcospereira Play: Prep for 2.8.0 release https://github.com/playframework/play-meta/issues/131
* [ ] @marcospereira Release Play 2.8.0 GA https://github.com/playframework/play-meta/issues/134
* [ ] Play: port samples using Akka to Akka Typed Actors
  * [x] @dwijnand play-scala-websocket-example [play-samples#62](https://github.com/playframework/play-samples/pull/62)
  * [x] @dwijnand play-java-websocket-example [play-samples#63](https://github.com/playframework/play-samples/pull/63)
  * [ ] @ignasi35 review state of samples using Play 2.8
    * [x] First pass: https://github.com/playframework/play-samples/pull/67
    * [ ] increase adoption of `scalacOptions := List("-Xfatal-warnings")` (not all samples enable it)
* [ ] @marcospereira QA from Lightbend Marketing team

## Lagom 1.6.0 Release

* [x] Lagom: Akka Persistence Typed docs [lagom#2387](https://github.com/lagom/lagom/issues/2387)
  * [x] @renatocaval Port the Scala tutorial to Java [lagom#2435](https://github.com/lagom/lagom/pull/2435)
    * [x] rewrite ref docs
    * [x] import java code from the lagom-samples
  * [x] @renatocaval Lagom: Migrating to Akka Persistence Typed
    * [x] Make all embedded code style-guide compliant (scala)
    * [x] Writeup of the migration process (java), port [lagom#2407](https://github.com/lagom/lagom/pull/2407) - https://github.com/lagom/lagom/pull/2464
    * [x] Make all embedded code style-guide compliant (java) - included in https://github.com/lagom/lagom/pull/2464
  * [ ] @renatocaval Review usage of term Aggregate. Maybe we should just use `Entity` [lagom#2482](https://github.com/lagom/lagom/pull/2482)
* [x] Adapt lagom-samples to use Akka Persistence Typed (1.6.x branch)
  * [x] @ignasi35 mixed-persistence: scala [lagom-samples#137](https://github.com/lagom/lagom-samples/pull/137) / java [lagom-samples#138](https://github.com/lagom/lagom-samples/pull/138)
  * [x] @ignasi35 couchbase-persistence scala [lagom-samples#141](https://github.com/lagom/lagom-samples/pull/141) / java [lagom-samples#139](https://github.com/lagom/lagom-samples/pull/139)
* [ ] @ignasi35 Prep for 1.6.0 release https://github.com/playframework/play-meta/issues/135
* [ ] @ignasi35 Release Lagom 1.6.0 GA https://github.com/playframework/play-meta/issues/136

### Post release tasks

* [ ] @marcospereira Play: review default branches
  * [ ] main repositories and standalone projects
  * [ ] seeds and samples
  * [ ] Update support table in https://portal.lightbend.com/LightbendPlatform/SupportedProjects
* [ ] @ignasi35 Lagom: review default branches
  * [ ] main repositories and standalone projects
  * [ ] seeds and samples
  * [ ] Update support table in https://portal.lightbend.com/LightbendPlatform/SupportedProjects

### Other

* [x] @dwijnand Fix reoccurring CI nightly failures
  * [x] CassandraClusteredPersistentEntitySpec [lagom#2080](https://github.com/lagom/lagom/issues/2080) [lagom#2460](https://github.com/lagom/lagom/issues/2460) [lagom#2485](https://github.com/lagom/lagom/pull/2485)
  * [x] confliciting akka version [lagom#2483](https://github.com/lagom/lagom/pull/2483)
  * [ ] CaffeineCacheApiSpec is flaky [play#9851](https://github.com/playframework/playframework/pull/9851)
* [ ] @ignasi35 (time-boxed) Study complexity of moving Lagom support from Akka-Persistence-Couchbase to Lagom repository [lagom/lagom#2481](https://github.com/lagom/lagom/issues/2481)
* [ ] Blog about the new minor releases
    * [ ] Play 2.8.0
    * [ ] Lagom 1.6.0

###### Metadata

* Dates: 2019-11-18 - 2019-11-29
* [Previous Sprint](https://github.com/playframework/play-meta/issues/130)
* Support Rota: Dale then Renato
* Person days: 26/30
  * Dale out 1/2 Tuesday + 1/2 Tuesday + last 2 days
  * Marcos: out 2019-11-29
