### ISSUE TITLE
Play Sprint Plan 2019-12-02

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#138]
## Play-WS Release

* [x] @renatocaval Release Play-WS [play-ws#420](https://github.com/playframework/play-ws/pull/420)
  * [x] 2.1.x backport and release (Play 2.8.x)
  * [x] 2.0.x backport and release (Play 2.7.x)

## Play 2.8.0 Release

* [x] @marcospereira Release Play 2.8.0 RC3 (with support for sbt `1.2.x`) [play-meta#134](https://github.com/playframework/play-meta/issues/134)
  * [x] Downgrade interplay to use sbt 1.2.8 [interplay#99](https://github.com/playframework/interplay/pull/99)
  * [x] Support sbt version 1.2.8+ in Play 2.8.0 and Lagom 1.6.0 - https://github.com/lagom/lagom/pull/2479#issuecomment-559851001
  * [ ] Play and Lagom should test using sbt 1.2.8 (aka minimum supported) and 1.3.4 (aka latest available) (cron builds only)
  * [ ] Needs validation in Lagom
* [ ] @marcospereira QA from Lightbend Marketing team

## Play 2.7.4 Release [play-meta#137](https://github.com/playframework/play-meta/issues/137)

* [x] @renatocaval with netty version bump [play#9871](https://github.com/playframework/playframework/pull/9871)
* [x] @renatocaval play-ws newest version from 2.0.x branch [play#9871](https://github.com/playframework/playframework/pull/9871)
* [x] Users get a warn when using deprecated functionally in Session [playframework#9865](https://github.com/playframework/playframework/pull/9865)
* [x] @renatocaval with Cookie.SameSite backport [playframework#9878](https://github.com/playframework/playframework/pull/9878)
* [x] Release Play 2.7.4

## Lagom 1.5.5 Release [play-meta#139](https://github.com/playframework/play-meta/issues/139)

* [x] @renatocaval with netty version bump [lagom#2498](https://github.com/lagom/lagom/pull/2498)
* [x] @renatocaval with fix for external services https [lagom#2500](https://github.com/lagom/lagom/pull/2500)
* [x] @renatocaval with Play 2.7.4 and play-ws, akka, netty, jackson, etc - [lagom#2501](https://github.com/lagom/lagom/pull/2501)

## Lagom 1.6.0 Release

* [x] @renatocaval Support for `https`-based external services in dev mode [lagom#2023](https://github.com/lagom/lagom/issues/2023)
* [x] Lagom: Akka Persistence Typed docs [lagom#2387](https://github.com/lagom/lagom/issues/2387)
  * [x] @renatocaval Review usage of term Aggregate. Maybe we should just use `Entity` [lagom#2482](https://github.com/lagom/lagom/pull/2482)
* [ ] @ignasi35 Prep for 1.6.0 release [play-meta#135](https://github.com/playframework/play-meta/issues/135)
  * [x] @ignasi35 Multiple version bumps [lagom#2479](https://github.com/lagom/lagom/pull/2479)
* [ ] @ignasi35 Release Lagom 1.6.0 GA https://github.com/playframework/play-meta/issues/136

### Post release tasks

* [ ] @marcospereira Play: review default branches
  * [ ] main repositories and standalone projects
  * [ ] seeds and samples
  * [ ] Update support table in https://portal.lightbend.com/LightbendPlatform/SupportedProjects
* [ ] @ignasi35 Lagom: review default branches
  * [ ] main repositories and standalone projects
  * [ ] seeds and samples
  * [ ] Update support table in https://portal.lightbend.com/LightbendPlatform/SupportedProjects

### Other

* [ ] @dwijnand Fix reoccurring CI nightly failures
  * [x] CaffeineCacheApiSpec is flaky [play#9851](https://github.com/playframework/playframework/pull/9851)
* [ ] @ignasi35 (time-boxed) Study complexity of moving Lagom support from Akka-Persistence-Couchbase to Lagom repository [lagom/lagom#2481](https://github.com/lagom/lagom/issues/2481)
* [ ] Blog about the new releases
    * [ ] Play 2.8.0
    * [ ] Lagom 1.6.0
* [ ] Meeting with Alpakka Team about Akka Persistence JDBC next steps

###### Metadata

* Dates: 2019-12-02 - 2019-12-13
* [Previous Sprint](https://github.com/playframework/play-meta/issues/133)
* Support Rota: Marcos then Ignasi
* Person days: 22/30
  * Dale out 1/2 Tuesday + 1/2 Tuesday + 3 day
  * Ignasi: out 4 days
