### ISSUE TITLE
Upgrade the builds from sbt 0.13 to sbt 1

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#14]
Strongly recommend users to use sbt 1 now. Explain support will be dropped in an upcoming version.

_This conversation was started by Eugene. We need to also migrate our own builds to use sbt 1._

## Issues & PRs

Not a comprehensive list of current issues and pull requests.

- [x] https://github.com/playframework/play-json/pull/145
- [x] https://github.com/playframework/cachecontrol/pull/23
- [x] https://github.com/playframework/play-ws/pull/210 and https://github.com/playframework/play-ws/pull/243
- [x] https://github.com/playframework/interplay/issues/54 / https://github.com/playframework/interplay/pull/60
- [x] https://github.com/playframework/twirl/pull/206
- [x] https://github.com/playframework/playframework/issues/8383 / https://github.com/playframework/playframework/pull/9001
- [x] https://github.com/lagom/lagom/issues/1329
- [x] https://github.com/lagom/lagom.github.io/issues/123 / https://github.com/lagom/lagom.github.io/pull/183
- [x] https://github.com/playframework/omnidoc/issues/19

**Comment by dwijnand** [comment]
All done. Specifically:

* [x]  Play [playframework/playframework#8383](https://github.com/playframework/playframework/issues/8383)
* [x]  Lagom [lagom/lagom#1329](https://github.com/lagom/lagom/issues/1329)
* [x]  lagom.com [lagom/lagom.github.io#183](https://github.com/lagom/lagom.github.io/pull/183)
* [x]  omnidoc [playframework/omnidoc#32](https://github.com/playframework/omnidoc/pull/32)
* [x]  play-slick [playframework/play-slick#465](https://github.com/playframework/play-slick/pull/465)
* [x]  scalatestplus-play [playframework/scalatestplus-play#110](https://github.com/playframework/scalatestplus-play/pull/110) and [playframework/scalatestplus-play#145](https://github.com/playframework/scalatestplus-play/pull/145)
