### ISSUE TITLE
Review Mergify rules

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#24]
We have discussed a few options for Mergify rules and here is what I remember so far. Feel free to add/modify it.

### Framework / Library Projects

- [x] WIP rule to block auto merge. Experiment with WipBot didn't work as expected
- [x] backport/forwardport driven by labels
- [x] ~squash only when label present~ (edit: squash by default, use label to opt-out 👇)
- [ ] merge instead of squash driven by labels (tracked in #25)
- [ ] Preserve PR title when merging/squashing (required Mergify PR - see #23)
- [ ] Preserve PR title when backporting (required Mergify PR - see #15)
- [x] CLA check, no automation without CLA 
- [x] dismiss review on PR update
- [x] ~dismiss merge label on PR update~
- [x] ~require at least 2 approvals (???) - I don't remember the decision on this~

### Sample Projects (Template Control rules)

- [ ] WIP rule to block auto merge. Experiment with WipBot didn't work as expected
- [ ] human-created PRs should use the same rules as in "Framework / Library Projects"

**Comment by renatocaval** [comment]
So far I got this done in:

## Already in place for Lagom and Play:
 * backport to maintenance branch
 * WIP rule

## Side projects. 
 * No backporting - since those project have low latency, I guess we don't really work with a 'maintenance' branch. Instead we merge on master and eventually we release from it. @marcospereira, can you confirm?

- [ ] https://github.com/playframework/play-slick/pull/463
- [ ] https://github.com/playframework/omnidoc/pull/31
- [ ] https://github.com/playframework/play-json/pull/243
- [ ] https://github.com/playframework/play-file-watch/pull/33 and https://github.com/playframework/play-file-watch/pull/34
- [ ] https://github.com/playframework/cachecontrol/pull/48
- [ ] https://github.com/playframework/interplay/pull/61
- [ ] https://github.com/playframework/scalatestplus-play/pull/139
- [ ] https://github.com/playframework/twirl/pull/207
- [ ] https://github.com/playframework/playframework.com/pull/269

I didn't touch the community driven repos. https://github.com/playframework/play-meta/blob/master/repos.md#community-driven

**Comment by renatocaval** [comment]
Add mergify on lagom projects:

Added mergify on Lagom projects. Most of them will get a slight different mergify file when they got managed by Template Control

- [ ] https://github.com/lagom/lagom-scala.g8/pull/50
- [ ] https://github.com/lagom/lagom-java.g8/pull/49
- [ ] https://github.com/lagom/online-auction-scala/pull/115
- [ ] https://github.com/lagom/lagom-java-sbt-chirper-example/pull/35
- [ ] https://github.com/lagom/lagom-java-maven-chirper-example/pull/31
- [ ] https://github.com/lagom/lagom-scala-grpc-example/pull/37
- [ ] https://github.com/lagom/lagom-java-grpc-example/pull/22
- [ ] https://github.com/lagom/lagom-java-openshift-smoketests/pull/13
- [ ] https://github.com/lagom/lagom-scala-openshift-smoketests/pull/17
- [ ] https://github.com/lagom/shopping-cart-java/pull/23
- [ ] https://github.com/lagom/shopping-cart-scala/pull/29
- [ ] https://github.com/lagom/ibm-integration-examples/pull/35
- [ ] https://github.com/lagom/lagom-akka-discovery-service-locator/pull/62
- [ ] https://github.com/lagom/lagom-recipes/pull/70

**Comment by dwijnand** [comment]
No remaining issues.

**Comment by dwijnand** [comment]
Well there's https://github.com/playframework/play-meta/issues/61, but let's close this aggregating issue.
