### ISSUE TITLE
Play Sprint Plan 2019-02-11

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#40]
[Previous sprint plans](https://github.com/lightbend/play-meta/issues?q=label:sprint-plan+sort:created-desc)

## Dates

- Starts: 2019-02-11
- Ends: 2019-02-22

## People & Days off

- @dwijnand:
    - 2019/02/18 1/2 day - Programming Reactive Systems course
    - 2019/02/19-21 Lightbend Reactive Architecture course
- @ignasi35
    - 2019/02/13 1 day - Madrid
- @marcospereira
    - Feb 18: Holiday (Family day) in Canada
- @renatocaval

------

# Objective & Tasks

The sections below group tasks per type.

## External tasks

- [x] @marcospereira  Bump Akka to 2.5.21 on `1.4.x` and release `1.4.11`
    - See [discuss](https://discuss.lightbend.com/t/cluster-fail-with-error-akka-version-must-be-the-same-across-all-modules-of-akka-that-you-are-using/3396)
    - Pull request: https://github.com/lagom/lagom/pull/1734
    - Should we wait for Akka 2.5.21? If so, this will be a release train including Play 2.6.x, 2.7.x, another Lagom 1.4.x and LBO (?).
    - [x] https://github.com/playframework/play-meta/issues/39 Release Lagom 1.4.11
        - [x] https://github.com/lagom/lagom.github.io/pull/172 Announce release 1.4.11
        - [x] https://github.com/lagom/online-auction-scala/pull/108 Lagom 1.4.11
        - [x] https://github.com/lightbend/reactive-platform-docs/pull/98 Lagom 1.4.11
        - [x] https://github.com/lagom/lagom-scala.g8/pull/44 Lagom 1.4.11
        - [x] https://github.com/lagom/lagom-java.g8/pull/46 Lagom 1.4.11
        - [x] https://github.com/lagom/lagom-java-maven-chirper-example/pull/27 Lagom 1.4.11
        - [x] https://github.com/lagom/lagom-java-sbt-chirper-example/pull/29 Lagom 1.4.11
        - [x] https://github.com/lightbend/reactive-platform-docs/pull/99 Lagom 1.4.11
- [x] @marcospereira Travis CI Migration
    - Issue https://github.com/lightbend/play-team/issues/111
    - [E-mail thread](https://groups.google.com/a/lightbend.com/forum/#!topic/play-team/QOlLpiECNWk)
    - Let's have a 2h timebox focusing first on Lagom organization. If it fast, then we can run for Play org too.

## Task post Play 2.7.0 release

- [x] Reformat & unnest [playframework/playframework#8992](https://github.com/playframework/playframework/issues/8992) @dwijnand
- [ ] @marcospereira will open a thread to discuss Slick future and its integration with Lagom

## Lagom 1.5.0 Milestone

Below is the list of issues and pull-requests for [Lagom milestone 1.5.0](https://github.com/lagom/lagom/milestone/35).

### ServiceLocator & Akka Management Integration

- [x] https://github.com/lagom/lagom/issues/1725 - Adds support for Akka Cluster Bootstrap
    - [ ] https://github.com/lagom/lagom/pull/1738 - Add Cluster Health Check
- [x] Create a test repo Central Park, based on lagom minimal
    - [x] https://github.com/lagom/lagom-scala-minimal-deployment-example/pull/1 - Removes LBO to add manual location and bootstrap
    - [x] https://github.com/lagom/lagom-scala-minimal-deployment-example/issues/3 - Prepare the sample to deploy on OpenShift
    - [x] Have a Java/Maven version of Lagom minimal - https://github.com/lagom/lagom-java-openshift-smoketests
- [x] https://github.com/lagom/lagom-akka-discovery-service-locator/issues/30 -  Document how to use it in README
- [x] https://github.com/lagom/lagom/issues/1733 - Document how Akka Management is used in Lagom 1.5.0 - done in https://github.com/lagom/lagom/pull/1738

### Tests

- [x] ~[lagom/lagom#1597](https://github.com/lagom/lagom/issues/1597) - Cassandra cannot connect to host in testkit~ - moved to 1.5.x, not priority for the moment.
- [x] https://github.com/lagom/lagom/issues/1608 - Write unit tests (sample code) for SSL in testkit - https://github.com/lagom/lagom/pull/1742
- [ ] https://github.com/lagom/lagom/pull/1607 - Adds SSL docs for devmode and tests

### gRPC

- [ ] https://github.com/lagom/lagom/issues/862 - gRPC integration
    - [ ] https://github.com/lagom/lagom/issues/1553 - Document gRPC support
    - [ ] https://github.com/lagom/lagom/issues/1550 - Document additional routers support
    - [ ] https://github.com/lagom/lagom/issues/1735 - Add reference documentation about the new Service Discovery - done in https://github.com/lagom/lagom/pull/1738
- [ ] https://github.com/lagom/lagom/issues/1595 - [EPIC] gRPC testkit
    - [ ] https://github.com/lagom/lagom/issues/1615 - Lagom-gRPC testkit for client side https://github.com/playframework/play-grpc/pull/51
- [ ] https://github.com/lagom/lagom/issues/1410 - [EPIC] Add support for HTTPS (needed for gRPC integration)
    - [ ] https://github.com/lagom/lagom/issues/1576 - Document how to use HTTPS/SSL in dev mode - https://github.com/lagom/lagom/pull/1607
    - [ ] https://github.com/lagom/lagom/issues/1589 - Document how to use HTTPS/SSL when deploying to production

### Misc

- [ ] Evaluate impact of Lagom 1.5.0 on Operations training:
    - [E-mail thread](https://groups.google.com/a/lightbend.com/forum/#!topic/play-team/d4-vOT-JDWA)

### Release

- [ ] #6 - Release Lagom 1.5.0
- [ ] Finish gRPC sample apps for Lagom #13

**Comment by ignasi35** [comment]
>  lagom/lagom#1589 - Document how to use HTTPS/SSL when deploying to production

This is a bit hairy and could fall out of this sprint. I think it is the least important aspect of the changes required in Documentation wrt Production and it's still WIP when considering OpenShift deployment in particular.
