### ISSUE TITLE
Play Sprint Plan 2019-02-25

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#42]
[Previous sprint plans](https://github.com/lightbend/play-meta/issues?q=label:sprint-plan+sort:created-desc)

## Dates

- Start: 2019-02-25
- End: 2019-03-08

## Absences

- @marcospereira - 5 days off from Mar 4-8 
- @renatocaval - 6 days off from Mar 1-8
- @ignasi35 - 2.5 days off (half Feb 28th, Mar 1, Mar 8)
- @dwijnand - 0.5 days busy doing https://www.edx.org/course/programming-reactive-systems

## Support

- [x] Dale will take of support Feb 28 and Mar 1.
- [x] Dale and Marcos switching support weeks from Mar 4-8 and Mar 11-15.

### Release Lagom 1.5-RC2 and Lagom 1.5

- [x] Release Lagom 1.5.0-RC2 - ([milestone](https://github.com/lagom/lagom/milestone/44) / [checklist](https://github.com/playframework/play-meta/issues/45)) @dwijnand
- [x] Lagom-gRPC testkit for client side https://github.com/playframework/play-grpc/pull/51 @ignasi35
- [x] Upgrade Lagom samples for upcoming Lagom 1.5 - https://github.com/playframework/play-meta/issues/13 @ignasi35 (fix online-auction branching!)
- [x] gRPC integration https://github.com/lagom/lagom/issues/862
    - [x] Document gRPC support https://github.com/lagom/lagom/issues/1553
        - [x] https://github.com/playframework/play-grpc/pull/53) @marcospereira
        - [x] https://github.com/playframework/play-grpc/pull/54
        - [x] https://github.com/lightbend/techhub/pull/254
        - [x] https://github.com/lightbend/example-code-service/pull/154
        - [x] https://github.com/lagom/lagom-java-grpc-example/pull/19
    - [x] Document additional routers support https://github.com/lagom/lagom/pull/1760 @renatocaval
- [ ] Migration Guide for Lagom 1.5
    - [ ] read, test & provide feedback on the [OpenShift Deployment Guide](https://developer.lightbend.com/guides/openshift-deployment/) ([repo](https://github.com/lightbend/openshift-deployment-guide))
        - [x] read @ignasi35 
        - [x] provide feedback @ignasi35 
        - [ ] test
    - [x] Check if we need to link to release notes for patch 1.4.x releases (given that they have some minor migration info) - @ignasi35 _"I did the review which include SBR, Slick and `akka-persistence-jdbc`. I opted for a general message: https://github.com/lagom/lagom/pull/1767"_ 
    - [x] Moving away from LBO: produce reference guide content and link from the Migration15.md - `You had this, you need that, see [page] for more details`
        - [x] When deploying to Kubernetes/OpenShift - https://github.com/lagom/lagom/pull/1774 (_just_ added a reference to LB guide to deploy on OpenShift)
        - [x] When not deploying to K8s/OS - https://github.com/lagom/lagom/pull/1774
        - [x] inter-service discovery https://github.com/lagom/lagom/pull/1765
        - [x] cluster bootstrap mechanisms https://github.com/lagom/lagom/pull/1765
        - [x] health checks https://github.com/lagom/lagom/pull/1765
        - [x] secret management https://github.com/lagom/lagom/pull/1765
        - [x] Lagom 1.5 won't work with LBO https://github.com/lagom/lagom/pull/1765
    - [x] Akka HTTP Management routes (link akka management docs so Lagom users can use all akka management routes available to them) - _the current docs in the Cluster page don't explicitly list the routes but link to the appropriate Akka pages already_
    - [x] See https://github.com/lagom/online-auction-java/pull/200 and https://github.com/lagom/online-auction-scala/pull/102 to check if there are some other changes we need to document - _@ignasi35 I've review the upgrades and found nothing relevant other than Play-specific changes_
- [ ] Release Lagom 1.5 ([milestone](https://github.com/lagom/lagom/milestone/35))
- [ ] Evaluate the impact of Lagom 1.5 on the Operations training ([Email thread](https://groups.google.com/a/lightbend.com/forum/#!topic/play-team/d4-vOT-JDWA))
- [ ] Open a thread to discuss Slick future and its integration with Lagom @marcospereira

**Comment by ignasi35** [comment]
Created https://github.com/lagom/lagom-java-sbt-chirper-example/issues/30 (related to migration out of LBO)

**Comment by ignasi35** [comment]
Unfinished/In-flight items:

 * in https://github.com/playframework/play-meta/issues/13#issuecomment-451893641 the task to upgrade Travis is incomplete.
 * move sample apps away from LBO (see https://github.com/playframework/play-meta/issues/42#issuecomment-467418588)

**Comment by ignasi35** [comment]
Unplanned/freestyle work:

- [x] release `akka-grpc` `0.6.0` 
- [ ] release `play-grpc` `0.6.0` (blocked by https://github.com/playframework/play-grpc/pull/62)
- [ ] upgrade play/lagom grpc samples (see https://github.com/playframework/play-grpc/pull/62#issue-259085852)
