### ISSUE TITLE
Play Sprint Plan 2019-03-11

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#51]
[Previous sprint plans](https://github.com/lightbend/play-meta/issues?q=label:sprint-plan+sort:created-desc)

## Dates

- Start: 2019-03-11
- End: 2019-03-22

## Absences

- @marcospereira: Support from Mar 11-15
- @renatocaval: Support from Mar 18-22
- @ignasi35: Out Mar 11
    - Study task: single day to learn more about Akka Typed

## Objectives/Tasks

- [x] Read, test & provide feedback on the [OpenShift Deployment Guide](https://developer.lightbend.com/guides/openshift-deployment/) ([repo](https://github.com/lightbend/openshift-deployment-guide))
    - [x] Read @ignasi35
    - [x] Provide feedback @ignasi35
    - [x] Test @renatocaval (with some smoketest by @ignasi35)
- [x] Verify whitesource.com to see if we need to update some dependency because of security issues.
    - there are 2 offenders: `commons-lang3:3.4` and `guava:19`/`guava:16.0.1`
    - [x] force eviction of Guava 19.0 https://github.com/lagom/lagom/pull/1777
    - [x] bump `maven-core` to bump the transitive `commons-lang3:3.4` https://github.com/lagom/lagom/pull/1778
    - [x] whitesource still reports `guava:16.0.1` though `sbt` lists that version as `evicted`. @ignasi35 
 
### Prep for Lagom 1.5.0

- [x] Test to migrate a Lagom 1.5.0 application and see how this impacts the migration guide @renatocaval 
- [x] Test a snapshot of Akka Management before 1.0.0 @ignasi35 
   - used a local build of lagom to deploy (successfully) `lagom-{scala-java}-openshift-smoketests`
- [x] Release Akka Management 1.0.0
- [x] Update Lagom to use Akka Management 1.0.0 @ignasi35 https://github.com/lagom/lagom/pull/1795

### From the [Lagom 1.5.0](https://github.com/lagom/lagom/milestone/35) milestone

- [x] https://github.com/lagom/lagom/issues/1772 / https://github.com/lagom/lagom/pull/1773
- [x] https://github.com/lagom/lagom/issues/1771
- [x] https://github.com/lagom/lagom/issues/1770 
   - [x] a) move content and complete `Highlights15` @ignasi35 https://github.com/lagom/lagom/pull/1779
   - [x] b) fix the LBO migration guide @renatocaval https://github.com/lagom/lagom/pull/1785
- [x] https://github.com/lagom/lagom/issues/1735

### Release Lagom 1.5.0

- [ ] [Tracking issue for the Lagom 1.5.0 release](https://github.com/playframework/play-meta/issues/6) @ignasi35 

### scalafmt & javafmt for Lagom

Using the same configurations we have for Play:

- [ ] master https://github.com/lagom/lagom/pull/1809 @marcospereira 
- [ ] 1.5.x
- [ ] 1.4.x

This must be done **after** releasing 1.5.0.

### New Labels for Backport

- [x] Make it clear that it needs to be backported to 2.6.x and 2.7.x in Play (status:needs-backport-2.6.x, etc.) https://github.com/playframework/playframework/pull/9083
- [x] Make it clear that it needs to be backported to 1.4.x and 1.5.x in Lagom (status:needs-backport-1.5.x, etc.) https://github.com/lagom/lagom/pull/1775

### Lagom & AdoptOpenJDK 11

- [ ] Use sbt 1 to build Lagom itself @dwijnand  https://github.com/lagom/lagom/issues/1329
    - [x] https://github.com/lagom/lagom/pull/1790 @marcospereira
- [x] Support for Java 11 @dwijnand https://github.com/lagom/lagom/issues/1417
    - [x] https://github.com/lagom/lagom/pull/1803
    - [x] https://github.com/lagom/lagom/pull/1802

### Play Examples for 2.6.x

- [x] Change https://www.playframework.com/documentation/2.6.x/Tutorials to have only the GitHub URL https://github.com/playframework/playframework/pull/9082
- [x] Remove 2.6.x from versions to query in playframework.com https://github.com/playframework/playframework.com/pull/264

### Scala 2.13

- [ ] https://github.com/akka/akka-grpc/issues/506
- [ ] https://github.com/playframework/play-grpc/issues/40

> Note: There are some dependencies outside of our control and we can ping them to see the current status/plan.

**Comment by marcospereira** [comment]
For the next Sprint: 

### Lagom sample applications

- [ ] Use templatecontrol to update Lagom samples:
    - [ ] Use AdoptOpenJDK 8
    - [ ] Update .travis.yml support exclusion for projects that have specific configuration
    - [ ] Mergify settings
    - [ ] Settings bot YAML

**Comment by TimMoore** [comment]
https://github.com/lagom/lagom/issues/1798 Complete the migration guide: https://www.lagomframework.com/documentation/1.5.x/scala/Migration15.html#Upgrading-a-production-system
