### ISSUE TITLE
Play Sprint Plan 2019-04-11

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#59]
[Previous sprint plans](https://github.com/lightbend/play-meta/issues?q=label:sprint-plan+sort:created-desc)

## Dates

- Start: 2019-04-15
- End: 2019-04-26

## Absences

- @marcospereira
- @renatocaval
- @ignasi35
- @dwijnand

Easter Friday 19 & Monday 22.

## Objectives/Tasks

- [x] Release Lagom 1.5.0: https://github.com/playframework/play-meta/issues/6
	- [x] release is done, only MiMa checks are left. Which is waiting for review here: https://github.com/lagom/lagom/pull/1866
- [x] Release 2.7.1: https://github.com/playframework/play-meta/issues/52
    - [x] Fix Play's snapshots build (probably related with current issue blocking us on release 2.7.1): 
        - [x] https://github.com/playframework/interplay/pull/69
        - [x] https://github.com/lightbend/vegemite/pull/16.
        - [x] https://github.com/lightbend/vegemite/pull/17
- [ ] Roadmap for Play & Lagom
- [ ] Scala 2.13.0-RC1
    - [x] [2.0.6 released] interplay: https://github.com/playframework/interplay/pull/67
    - [x] [1.4.1 released] twirl: https://github.com/playframework/twirl/pull/213 https://github.com/playframework/play-json/pull/257
    - [x] ssl-config: https://github.com/lightbend/ssl-config/pull/161
    - [x] [2.7.3 relesed] play-json: https://github.com/playframework/play-json/pull/254
    - [x] [1.1.6 released] cachecontrol: https://github.com/playframework/cachecontrol/pull/55 https://github.com/playframework/cachecontrol/pull/56
    - [x] play-doc https://github.com/playframework/play-doc/pull/49
    - [ ] playframework/playframework: blocked by https://github.com/akka/akka/issues/26691
- [x] Fix Play's integration tests on Java 11 @dwijnand https://github.com/playframework/playframework/issues/9188
- [ ] OpenShift deployment guide for Play (Who should take on it?)
- [ ] Samples reorganisation
    - [ ] Lagom sample app diet
    - [x] Play samples repo consolidation (+TemplateControl/ExampleCodeService) @dwijnand
    - [ ] Lagom samples repo consolidation (+TemplateControl/ExampleCodeService)
    - [ ] Lagom recipes extraction & archival (+TemplateControl/ExampleCodeService) - requires reviewing Lagom docs (see [this ref](https://www.lagomframework.com/documentation/current/scala/PersistentEntity.html#Choosing-a-database) ) 
- [ ] JUnit 5 support
- [ ] Low-hanging fruit
    - [x] ~link akka javadoc from play javadoc~ _(this is not low-hanging fruit, it requires using a JDK 11 version of `javadoc`)_ https://github.com/playframework/playframework/issues/9112

**Comment by ignasi35** [comment]
_freestyling_: 

 * https://github.com/lagom/lagom/pull/1864 . (docs Couchbase and SQLServer)
