### ISSUE TITLE
Play Sprint Plan 2019-05-13

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#73]
* [x] Final touchups and hand over the Play 2.8 / Lagom 1.6 roadmap and product plan @dwijnand
* [x] Fix Lagom nightly jobs (Still failing with an OOM error) @ignasi35
* [ ] Upgrade the Play/Lagom ecosystem to Scala 2.13.0-RC2 @dwijnand / @marcospereira 
    * [ ] https://github.com/playframework/playframework/issues/9336 Play ecosystem
    * [x] Upgrade Slick's dependency to scala-collection-compat 2.0.0 https://github.com/slick/slick/pull/2040
    * [ ] Slick 3.3.x backport: https://github.com/slick/slick/pull/2031
* [x] `Column family ID mismatch` https://github.com/lagom/lagom/pull/1916 - Fix seems to not solve the issue entirely
    * [x] ~Merge when users to confirm it fixes the bug~
    * [x] ~Release Lagom 1.4.x~
    * [x] ~Forwardport to 1.5.x and master~
    * despite customer still hitting `Column family ID mismatch`, other user observed [improvements](https://discuss.lightbend.com/t/cassandra-column-family-id-mismatch-at-startup/3721/14). I think this needs more testing.
* [x] Roll out play-ws bug-fix
    * [x] Bump Play 2.6.x to play-ws v1.1.13 https://github.com/playframework/playframework/pull/9300 @ignasi35
    * [x] wait for confirmation 1.1.13 fixes the bug
    * [x] Release Play 2.6.23 w/ play-ws bump https://github.com/playframework/play-meta/issues/74 @renatocaval 
    * [x] Release Lagom 1.4.13 w/ Play bump https://github.com/lagom/lagom/pull/1937 @renatocaval https://github.com/playframework/play-meta/issues/75
    * [x] Forward port to 2.0.x (https://github.com/playframework/play-ws/pull/343)
	* [x] Forward port to master (https://github.com/playframework/play-ws/issues/344)
    * [x] Release play-ws 2.0.4 w/ forward-port
* [x] Fix ssl-config to work with Java 11 (see play-scala-tls-example failure) https://github.com/playframework/play-ws/pull/346 @dwijnand
* [x] Shopping-cart
    * [x] Split Minishift deployment in three Travis' jobs (paradox guide). Use Travis stages if necessary.
    * [x] Implement Read-side processor and testkit (take from online auction)
          https://github.com/lagom/lagom-samples/pull/57
* [x] Automate the deployment of Lagom smoke tests (unarchive) in Central Park 2 @ignasi35 
    * [x] automate deployment and test os smoketest scala on CP2 https://github.com/lagom/lagom-scala-openshift-smoketests/pull/23
    * [x] automate deployment and test os smoketest java on CP2 - WONTDO: repetitive task (smoketests are archived anyway)
* [x] Change references to lagom-recipes to lagom-samples https://github.com/lagom/lagom/issues/1921 @dwijnand
* [ ] Lagom master branch using Akka 2.6 milestones: https://github.com/lagom/lagom/pull/1904
    * [ ] Should already include migration guide for Lagom 1.6.
* [x] Sync Play 2.8.0 and Lagom 1.6.0 milestones to the approved roadmap @dwijnand

###### Metadata

* Dates: 2019-05-13 - 2019-05-24
* [Previous Sprint](https://github.com/playframework/play-meta/issues/63)
* Support Rota: Renato then Ignasi
* Person days: 
	* 27/30 (@marcospereira out 3 days)
    * Akka Projection (@renatocaval 20/03) - finalize Alpakka Kafka experiment
