### ISSUE TITLE
Play Sprint Plan 2019-05-27

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#82]
* [x] Publish the Play 2.8 and Lagom 1.6 roadmap in 1 Discourse thread, with:  (@marcospereira)
  * our release objectives
  * linking to milestones
  * inviting external maintainers and contributors to highlight issues they are interested to work on
  * tweet the link
  * Gitter message with the link
* [x] Finish releasing Play 2.8.0-M1 https://github.com/playframework/play-meta/issues/83 @marcospereira 
  * [x] Spend 1/2 hour to update play-samples to use Play 2.8.0-M1 https://github.com/playframework/play-samples/pull/16 @ignasi35
* [ ] Lagom on Scala 2.13.0-RC2 https://github.com/lagom/lagom/issues/1957
  * [x] Slick 3.3.x backport: https://github.com/slick/slick/pull/2031 @marcospereira
  * [x] https://github.com/akka/akka-persistence-cassandra/pull/482
  * [ ] https://github.com/lagom/lagom/pull/1454 (without Kafka support) @ignasi35 
* [x] Lagom ~1.6.0-M1~ 1.6.0-M2 release (without 2.13 artifacts) @renatocaval
  * [x] master branch using Akka 2.6 milestones (should already include migration guide for Lagom 1.6): https://github.com/lagom/lagom/pull/1904
  * [x] Use Play 2.8.0-M1: https://github.com/lagom/lagom/pull/1962
  * [x] make the release: https://github.com/playframework/play-meta/issues/84
* [x] Define an agreed support rota's daily checklist (see internal notes) @dwijnand @marcospereira 
* [x] [Lagom 1.5 bugfix] Fix akka.discovery.method in dev-mode https://github.com/lagom/lagom/pull/1951 @renatocaval
* [x] Play on Java 11 https://github.com/playframework/playframework/issues/9261 @dwijnand 
  * [x] fix play-scala-tls-example https://github.com/playframework/play-samples/issues/17 @ignasi35 @marcospereira @dwijnand 
  * [x] https://github.com/playframework/playframework/pull/8828
* [x] Lagom on Java 11 https://github.com/lagom/lagom/issues/1417
  * [x] Cassandra support (tests are passing), but we need to validate dev mode too  - https://github.com/lagom/lagom/issues/1975 @marcospereira 
* [ ] Switch to Akka 2.6's Jackson serializer https://github.com/lagom/lagom/issues/1931 @ignasi35
  * [ ] Review @patriknw's https://github.com/lagom/lagom/pull/1955

###### Metadata

* Dates: 2019-05-27 - 2019-06-07
* [Previous Sprint](https://github.com/playframework/play-meta/issues/73)
* Support Rota: Marcos (Mon) then Dale (Tue-Mon) then Marcos (Tue-Sun)
* Person days: 22/30 
  * Dale out 3 days
  * Ignasi 3 days
  * Renato 2 days (30/05 and 31/05)

**Comment by marcospereira** [comment]
- Roadmap:
  - Topic: https://discuss.lightbend.com/t/play-2-8-lagom-1-6-roadmap/4276
  - Tweet: https://twitter.com/playframework/status/1133110952776339456
  - Gitter: https://gitter.im/playframework/playframework?at=5cec4bef9d64e537bc2056d4
