### ISSUE TITLE
Play Sprint Plan 2019-06-17

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#85]
- [x] Switch to Akka 2.6's Jackson serializer https://github.com/lagom/lagom/issues/1931 @ignasi35
  - [x] Review @patriknw's https://github.com/lagom/lagom/pull/1955
- [x] Run Play's documentation tests with Java 11 https://github.com/playframework/playframework/issues/9366 @ignasi35
- [x] sbt 1.3.0-RC2 pre-release testing @dwijnand 
	- [x] Smoke test Lagom and Play builds in sbt 1.3.0-RC2 https://github.com/lagom/lagom/pull/1996 & https://github.com/playframework/playframework/pull/9396
	- [x] Smoke test Lagom and Play samples in sbt 1.3.0-RC2 https://github.com/lagom/lagom-samples/pull/71 & https://github.com/playframework/play-samples/pull/29
    	- [x] ~Check how new sbt turbo mode will affect dev mode in Lagom and Play~
			* Turbo mode is even more hard-core classloader changes,
			* pushed to the next round of testing
	- [x] Smoke test interplay in sbt 1.3.0-RC2 - https://github.com/playframework/interplay/pull/79
	- [x] Reproduce & report ctrl-C problem
- [x] Scala 2.13 upgrade
	- [x] Slick @renatocaval
    - [x] lightbend/ssl-config @marcospereira
    - [x] playframework/play-ws @marcospereira
    - [x] playframework/playframework
    - [x] playframework/omnidoc
    - [x] playframework/play-slick https://github.com/playframework/play-slick/pull/482
    - [x] playframework/scalatestplus-play
    - [x] ~playframework/play-grpc~ - this won't be possible because we will need a Lagom build for 2.13 and we only plan it for Lagom 1.6.0
    - [x] playframework/play-samples (just Play 2.7.3 - https://github.com/playframework/play-samples/pull/31)
    - [x] playframework/play-samples (just 2.13, no cross-build - https://github.com/playframework/play-samples/pull/32)
    - [x] dnvriend/akka-persistence-jdbc - https://github.com/dnvriend/akka-persistence-jdbc/pull/238
- [x] Akka 2.6.0-M3 upgrade (requires scala 2.13)
    - [x] playframework/play-ws - https://github.com/playframework/play-ws/pull/356
    - [x] playframework/playframework - https://github.com/playframework/playframework/pull/9397
    - [x] lagom/lagom - https://github.com/lagom/lagom/pull/1997
- [x] Run Play's documentation tests using Scala 2.13 https://github.com/playframework/playframework/issues/9413
- [x] Akka 2.6's Coordinated Shutdown, review impact on of `ActorSystem#terminate` calling CS
	- [x] playframework/playframework#9275 @dwijnand & @ignasi35
	- [x] lagom/lagom#1932 @dwijnand & @ignasi35
- [x] https://github.com/lagom/lagom/pull/2007 Adopt ddata as default (cluster shutdown with opt-out/back to persistent sharding) @ignasi35
- [ ] lagom/lagom#1933/https://github.com/lagom/lagom/issues/1986 Switch to Artery as default remote transport @renatocaval & @ignasi35

###### Metadata

* Dates: 2019-06-17 - 2019-06-28
* [Previous Sprint](https://github.com/playframework/play-meta/issues/82)
* @marcospereira out from 2019-06-17 to 2019-06-21
* @renatocaval out from 2019-06-26 to 2019-06-27 - pipelines team meeting - partially available
* @ignasi35 out 1 day
* @dwijnand out 1 day
* Support Rota: @ignasi35 then @marcospereira
* Person days: 22/30

**Comment by WellingR** [comment]
akka-persistence-jdbc v3.5.2 is now available!
