### ISSUE TITLE
Play Sprint Plan 2019-07-01

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#89]
* [x] Lagom: Switch to Artery as default remote transport @renatocaval & @ignasi35 https://github.com/lagom/lagom/issues/1986
* [x] Lagom: [Release 1.6.0-M3](https://github.com/playframework/play-meta/issues/90), using Play 2.8.0-M2 & Akka 2.6.0-M3 (late) @ignasi35 
* [x] Play: Upgrade to Akka 2.6.0-M4 (2nd week) https://github.com/playframework/playframework/pull/9452
* [x] Play: Release 2.8.0-M3 (2nd week)
* [ ] Scala 2.13 upgrade: more progress
    * [x] Lagom on 2.13, with kafka-server for Scala 2.12 only https://github.com/lagom/lagom/pull/1454 @dwijnand
	* [x] Play: Build REST API samples with Scala 2.13 when Gatling moves to 2.13 https://github.com/playframework/play-samples/pull/38 @marcospereira 
	* [ ] Play: Build gRPC samples with Scala 2.13 when upstream deps are ready for 2.13 https://github.com/playframework/play-samples/issues/33 @marcospereira 
* [x] Java 11 support: the last bits
	* [x] Lagom: Run samples on Java 11 https://github.com/lagom/lagom-samples/pull/75  @marcospereira 
* [x] Update seeds (ddata & serialisation bindings): (do it in `master` and maintain repo branches)
    * [x] Lagom: Adjust Java seed: https://github.com/lagom/lagom-scala.g8/issues/57
    * [x] Lagom: Adjust Scala seed: https://github.com/lagom/lagom-java.g8/issues/56
* [ ] Lagom: Add an API to pause/restart read-side processors https://github.com/lagom/lagom/issues/1744 @ignasi & @renatocaval
* [ ] Lagom: Upgrade to APC 0.9x https://github.com/lagom/lagom/pull/1512
* [ ] Play: DI for typed actors https://github.com/playframework/playframework/issues/8999 @marcospereira

###### Metadata

* Dates: 2019-07-01 - 2019-07-12
* [Previous Sprint](https://github.com/playframework/play-meta/issues/85)
* Support Rota: Dale then Renato
* Person days: 24/30

**Comment by ignasi35** [comment]
```diff
-  Scala 2.13 upgrade: the last bits
+  [play] Scala 2.13 upgrade: the last bits
```
There are a few open fronts for Lagom to be 2.13 complete.
