### ISSUE TITLE
Play Sprint Plan 2019-07-15

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#95]
- [ ] [EPIC] lagom/lagom#2052 Lagom: Add an API to pause/restart read-side processors @ignasi35 & @renatocaval
    - [x] lagom/lagom#2037 Introducing replicated projection registry @ignasi35
    - [x] lagom/lagom#1744 implement pause and resume @ignasi35
    - [x] lagom/lagom#2050 Review contents of `cluster-extensions-*` and rename it @renatocaval
    - [ ] lagom/lagom#2048 Document API
    - [ ] lagom/lagom#2049 Ref docs and migration guide
- [x] Lagom: Upgrade to APC 0.9x lagom/lagom#1512
    - [x] Document that we recommend a full cluster shutdown when upgrading
    - [x] Locally test seeds after the upgrade to ensure they are not failing when running with Java 11
- [ ] Play: DI for typed actors playframework/playframework#8999 @dwijnand @marcospereira
- [ ] Lagom: update the docs to remove old/unmaintained examples @dwijnand
- [x] playframework/playframework#9480 Switch to the default dispatcher in Akka 2.6 @dwijnand
- [x] playframework/playframework#9383 Switch to Akka 2.6's Jackson serializer @marcospereira & @ignasi35
- [ ] playframework/playframework#9278 Play CQRS / Event Sourcing (incubating module)
	- [ ] playframework/playframework#9277 DI for ClusterSharding Typed
    - [ ] New API design @renatocaval + @ignasi35
		* output is a well-documented list of tasks for this epic
- [x] playframework/play-meta#94 Drop strict merging & re-enable branch builds
	- [x] lagom/lagom#2059 @renatocaval
	- [x] re-enable lagom 1.5.x https:// https://github.com/lagom/lagom/pull/2092 @dwijnand
	- [x] re-enable lagom 1.4.x https://github.com/lagom/lagom/pull/2093 @dwijnand
	- [x] drop strict merging in Play playframework/playframework#9483 @dwijnand
	- [x] re-enable branch builds in play master playframework/playframework#9482 @dwijnand
	- [x] re-enable branch builds in play 2.7.x playframework/playframework#9485 @dwijnand
	- [x] re-enable branch builds in play 2.6.x playframework/playframework#9486 @dwijnand

--- 

###### Metadata

* Dates: 2019-07-15 - 2019-07-26
* Previous Sprint: playframework/play-meta#89
* Support Rota: Marcos then Ignasi
* Person days: 25.5/30
	* Dale off 15-16
	* Ignasi 50%(?) off 15, 100% off 16
    * Renato off on 26

**Comment by marcospereira** [comment]
I will leave this as a comment so that we can edit the issue next Monday instead:

### Scala 2.13:

- There is an upcoming release of Akka HTTP and Akka gRPC that we can use to do a release of Play gRPC and finish the move of Play samples to Scala 2.13.
- For Lagom samples (https://github.com/lagom/lagom-samples/issues/80), there is gRPC and also Akka Persistence Couchbase: https://github.com/akka/akka-persistence-couchbase/pull/221.

### Java 11

- Lagom seeds are failing for Java 11 (related to Cassadra). I'm pretty confident that these will be fixed when upgrading to Akka Persistence Cassandra 0.9.x.
- We still have some projects allowing Java 11 failures in our builds. It could be good to remove these from Travis configuration to track possible regressions better.

**Comment by dwijnand** [comment]
Proposal: tear the lagom part of play-grpc out of play-grpc and into lagom/lagom (keep it as an incubating module), thus making play's grpc samples not depend on lagom (indirectly).

**Comment by renatocaval** [comment]
> Locally test seeds after the upgrade to ensure they are not failing when running with Java 11

I tested it manually with a local build and Java 11 and it works, however I got messages like:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/Users/renato/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.24.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.cassandra.utils.FBUtilities (file:/Users/renato/Sources/tmp/hello-world/target/embedded-cassandra/cassandra-bundle.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of org.apache.cassandra.utils.FBUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This is not related to Cassandra though.

**Comment by marcospereira** [comment]
Well, one of the problems is indeed related to Cassandra:

```
WARNING: Illegal reflective access by org.apache.cassandra.utils.FBUtilities (file:/Users/renato/Sources/tmp/hello-world/target/embedded-cassandra/cassandra-bundle.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of org.apache.cassandra.utils.FBUtilities
```

But there is nothing we can do right now, and there are other places where dependencies are raising similar warnings. So I think we are good to go here.
